// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:5e23a64f-b129-4909-9850-bcdc2b086edc',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'twostepauth-hosting-mobilehub-243857704',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd10m01odgm32mb.cloudfront.net',
    'aws_mobile_analytics_app_id': '8cfed5fc96a448b19eac247cb63028ad',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '336fa7e9-2bc4-11e8-959f-95313045fdb1',
    'aws_project_name': 'TwoStepAuth',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'twostepauth-mobilehub-243857704',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_whYAbn5wT',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '6s42vtfp3vvap0uk7v9tuc2hkm',
}

export default awsmobile;
